
# services:
#   node-app:
#     image: url-shortner-node-app
#     build: .
#     ports:
#       - "5001:5001"
#     depends_on:
#       - redis
#       - mongodb
#     environment:
#       - MONGO_URI=mongodb://mongodb:27017/url-shortner
#     networks:
#       - mynetwork

#   redis:
#     image: redis:7.4.2
#     networks:
#       - mynetwork
#     ports:
#       - "6379:6379"

#   mongodb:
#     image: mongo:latest
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongodb_data:/data/db
#     networks:
#       - mynetwork

# networks:
#   mynetwork:
#     driver: bridge

# volumes:
#   mongodb_data:

services:
  node-app:
    image: url-shortner-node-app
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - redis
    networks:
      - mynetwork

  redis:
    image: redis:7.4.2
    networks:
      - mynetwork
    ports:
      - "6379:6379"

networks:
  mynetwork:
    driver: bridge



